image: node:lts-alpine

stages:
  - init
  - build
  - test
  - deploy
  
variables:
  ARCHIVE_NAME: rh
  TRIGGER_CACHE: "on"

npm_cache:
  stage: init
  tags:
    - runner-java
  script:
    - node -v
    - npm install
  cache:
    key: node_modules
    paths:
      - node_modules/
    policy: push
  rules:
    - changes: 
        - package.json
    - if: $TRIGGER_CACHE == "on"

build:
  stage: build
  tags:
    # - dind
    - runner-java
  before_script:
    - apk add --update xz
    - npm cache clean --force
  script:
    - npm run build
    - mv build $ARCHIVE_NAME
    - cd $ARCHIVE_NAME
    - tar -cJf "../$ARCHIVE_NAME.tar.xz" ./*  
  artifacts:
    expire_in: 1 hour
    paths:
      - "$ARCHIVE_NAME.tar.xz"
  cache:
    key: node_modules
    untracked: true
    policy: pull

archive:
  image: lgatica/openssh-client
  stage: deploy
  tags:
    # - dind
    - runner-java
  script:
    - echo "$ARCHIVE_PKEY" > archive_pkey
    - chmod 400 archive_pkey
    - chmod 700 .
    - echo "put -rp $ARCHIVE_PATH/$ARCHIVE_NAME.tar.xz $ARCHIVE_NAME.tar.xz" > archive_batch
    - >
      sftp
      -i archive_pkey
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
      -b archive_batch
      $ARCHIVE_USER@$ARCHIVE_HOST
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
